apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wasp-authentication-service.fullname" . }}-config
  labels:
    {{- include "wasp-authentication-service.labels" . | nindent 4 }}
data:
  port: {{ .Values.config.port | quote }}
  logLevel: {{ .Values.config.logLevel | quote }}
  dbHost: {{ include "wasp-authentication-service.postgresql.fullname" . }}
  dbPort: {{ .Values.config.dbPort | quote }}
  dbName: {{ .Values.config.dbName }}
